Add files via upload

diff --git a/pdftexter b/pdftexter
--- a/pdftexter
+++ b/pdftexter
@@ -11,34 +11,33 @@ param2=$2
 param3=$3
 param4=$4
 
-if [ ! -e /usr/local/bin/gs ]; then
+if [ ! -e "/usr/local/bin/gs" ]; then
   echo ""
   echo "System requirement: Ghostscript"
   exit 1
 fi
 
-if [ ! -e /usr/local/bin/tesseract ]; then
+if [ ! -e "/usr/local/bin/tesseract" ]; then
   echo ""
   echo "System requirement: Tesseract"
   exit 1
 fi
 
-
 if [ "$param1" = "-h" ]; then
   echo ""
-  echo "Usage: pdftexter [file] -- [firstpage] [lastpage]"
+  echo "Usage: pdftexter [file] -- [firstpage]? [lastpage]?"
   exit 0
 fi
 
 if [ "X$param1$param2$param3$param4" = "X" ]; then
   echo ""
-  echo "Usage: pdftexter [file] -- [firstpage] [lastpage]"
+  echo "Usage: pdftexter [file] -- [firstpage]? [lastpage]?"
   exit 0
 fi
 
 #echo "converting.."
 
-if [ ! -e $param1 ]; then
+if [ ! -e "$param1" ]; then
   echo ""
   echo "$param1 doesn't exist."
   exit 1
@@ -51,7 +50,7 @@ else
   res=`echo $param2|grep -e ^/$testyear/`
   if [ "X$res" = "X" ]; then
     echo ""
-    echo "Usage: pdftexter [file] -- [firstpage] [lastpage]"
+    echo "Usage: pdftexter [file] -- [firstpage]? [lastpage]?"
     echo ""
     echo "Invalid param2."
     exit 1
@@ -60,9 +59,26 @@ else
 fi
 
 if [ "X$param3$param4" != "X" ]; then
+
+  if [ "X$param4" = "X" ]; then
+    param4=$param3
+  fi
+
+	if (( $param3 > 2000 )); then
+		echo ""
+		echo "Invalid firstpage."
+		exit 1
+	fi
+
+	if (( $param4 > 2000 )); then
+		echo ""
+		echo "Invalid lastpage."
+		exit 1
+	fi
+
 	if (( $param3 > $param4 )); then
 		echo ""
-		echo "Usage: pdftexter [file] -- [firstpage] [lastpage]"
+		echo "Usage: pdftexter [file] -- [firstpage]? [lastpage]?"
 		echo ""
 		echo "Invalid range."
 		exit 1
@@ -98,15 +114,18 @@ if [ "X$param3$param4" = "X" ]; then
     printf "Type a page or a range: " 
     read param3 param4
     if [ "X$param3$param4" = "X" ]; then
-      echo "We can't proceed.. bye!"
+      echo "bye."
       exit 1
     else
+
+      if [ "X$param4" = "X" ]; then
+        param4=$param3
+      fi 
+
       printf .
-			if [ "X$param4" = "X" ]; then
-				gs -dBATCH -dNOPAUSE -dFirstPage=$param3 -dLastPage=$param3 -sDEVICE=tiffgray -r200x200 -sOutputFile="$root/cache.pdftexter/$bookmd5/.$mydate-output%d.tiff" $param1 > /dev/null
-			else
-				gs -dBATCH -dNOPAUSE -dFirstPage=$param3 -dLastPage=$param4 -sDEVICE=tiffgray -r200x200 -sOutputFile="$root/cache.pdftexter/$bookmd5/.$mydate-output%d.tiff" $param1 > /dev/null
-			fi 
+
+  		gs -dBATCH -dNOPAUSE -dFirstPage=$param3 -dLastPage=$param4 -sDEVICE=tiffgray -r200x200 -sOutputFile="$root/cache.pdftexter/$bookmd5/.$mydate-output%d.tiff" $param1 > /dev/null
+
     fi
   else
 		#if [ -d $root/cache.pdftexter ]; then
@@ -118,12 +137,11 @@ if [ "X$param3$param4" = "X" ]; then
     exit 1
   fi
 else 
+
   printf .
-  if [ "X$param4" = "X" ]; then
-    gs -dBATCH -dNOPAUSE -dFirstPage=$param3 -dLastPage=$param3 -sDEVICE=tiffgray -r200x200 -sOutputFile="$root/cache.pdftexter/$bookmd5/.$mydate-output%d.tiff" $param1 > /dev/null
-  else
-    gs -dBATCH -dNOPAUSE -dFirstPage=$param3 -dLastPage=$param4 -sDEVICE=tiffgray -r200x200 -sOutputFile="$root/cache.pdftexter/$bookmd5/.$mydate-output%d.tiff" $param1 > /dev/null
-  fi 
+
+  gs -dBATCH -dNOPAUSE -dFirstPage=$param3 -dLastPage=$param4 -sDEVICE=tiffgray -r200x200 -sOutputFile="$root/cache.pdftexter/$bookmd5/.$mydate-output%d.tiff" $param1 > /dev/null
+
 fi
 
 if [ -e "$root/cache.pdftexter/$bookmd5/$mydate-final.txt" ]; then
